[2023-01-14T12:33:00.887+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-14T12:32:57.537143+00:00 [queued]>
[2023-01-14T12:33:00.911+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-14T12:32:57.537143+00:00 [queued]>
[2023-01-14T12:33:00.912+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T12:33:00.913+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-14T12:33:00.915+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T12:33:00.966+0000] {taskinstance.py:1304} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-14 12:32:57.537143+00:00
[2023-01-14T12:33:00.984+0000] {standard_task_runner.py:55} INFO - Started process 30741 to run task
[2023-01-14T12:33:01.016+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-14T12:32:57.537143+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm9zp8ngb']
[2023-01-14T12:33:01.018+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask is_api_available
[2023-01-14T12:33:01.284+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-14T12:32:57.537143+00:00 [running]> on host 35e95982c619
[2023-01-14T12:33:01.732+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T12:32:57.537143+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T12:32:57.537143+00:00
[2023-01-14T12:33:01.737+0000] {http.py:122} INFO - Poking: api/
[2023-01-14T12:33:01.786+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-01-14T12:33:01.797+0000] {http.py:150} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-14T12:33:02.314+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2023-01-14T12:33:02.372+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230114T123257, start_date=20230114T123300, end_date=20230114T123302
[2023-01-14T12:33:02.475+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-14T12:33:02.569+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
