[2023-01-14T13:53:55.823+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-14T13:51:44.200723+00:00 [queued]>
[2023-01-14T13:53:55.850+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-14T13:51:44.200723+00:00 [queued]>
[2023-01-14T13:53:55.855+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T13:53:55.857+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-14T13:53:55.861+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T13:53:55.912+0000] {taskinstance.py:1304} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-14 13:51:44.200723+00:00
[2023-01-14T13:53:55.923+0000] {standard_task_runner.py:55} INFO - Started process 34504 to run task
[2023-01-14T13:53:55.954+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-14T13:51:44.200723+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwficzie5']
[2023-01-14T13:53:55.968+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask is_api_available
[2023-01-14T13:53:56.160+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-14T13:51:44.200723+00:00 [running]> on host 35e95982c619
[2023-01-14T13:53:56.370+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T13:51:44.200723+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T13:51:44.200723+00:00
[2023-01-14T13:53:56.373+0000] {http.py:122} INFO - Poking: api/
[2023-01-14T13:53:56.392+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-01-14T13:53:56.397+0000] {http.py:150} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-14T13:53:56.774+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2023-01-14T13:53:56.797+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230114T135144, start_date=20230114T135355, end_date=20230114T135356
[2023-01-14T13:53:56.880+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-14T13:53:56.954+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
